'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    /*
      Add altering commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      */
    return queryInterface.bulkInsert('Spots', [
      { id: 1,
        userId: 1,
        description: "The home — its original address was 112 Ocean Ave. but was changed to 108 to deter tourists — was purchased by George and Kathy Lutz one year after the murders. But they ditched the property after only one month due to reported paranormal activity, which inspired a 1977 book and 1979 movie.",
        address: "108 Ocean Ave, Amityville, NY 11701",
        pricePerNight: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 2,
        userId: 1,
        description: "The home — its original address was 123 Scary Avenue. but was changed to deter tourists — was purchased by George and Kathy Lutz one year after the murders. But they ditched the property after only one month due to reported paranormal activity.",
        address: "999 Scary Ave, Scary Town, NY 11701",
        pricePerNight: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 3,
        userId: 1,
        description: "Brave people only",
        address: "123 Spooky Rd, Scary Town, CA 33321",
        pricePerNight: 15,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      { id: 4,
        userId: 1,
        description: "Brave people only.",
        address: "999 Scary Ave, Scary Town, MA 12344",
        pricePerNight: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 5,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "44 Lair Ln, Scary Town, AL 43243",
        pricePerNight: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 6,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "44 Blackcat Blvd, Scary Town, AL 43243",
        pricePerNight: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 7,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "44 Blackcat Drive, Scarytopia, OR 43243",
        pricePerNight: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 8,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "21 Don't Stay Here Drive, Scary Town, AK 43243",
        pricePerNight: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 9,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "887 Creepy Blvd, Scary Town, MT 55555",
        pricePerNight: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 10,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "105 Demon Drive, Long Beach, CA 90805",
        pricePerNight: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 11,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "5609 House Ln, Scary Town, PA 43243",
        pricePerNight: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 12,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "845 Ghost Rd, Scary Town, ME 43243",
        pricePerNight: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 13,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "55 SpoOoOoky Ln, Monster Town, IL 99999",
        pricePerNight: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 14,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "123 Lair Ln, Scary Town, AL 12345",
        pricePerNight: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 15,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "666 Death Drive, Long Beach, CA 90808",
        pricePerNight: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 16,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "432 Seed Rd, Made Up Place, CA 97439",
        pricePerNight: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 17,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "44 Villain Ln, Scary Town, KY 43243",
        pricePerNight: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 18,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "55 Spectre Ln, Scary Town, AL 43243",
        pricePerNight: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { id: 19,
        userId: 1,
        description: "Don't stay here if you are scared of ghosts.",
        address: "23 Last Rd, Scary Town, AL 22222",
        pricePerNight: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      */
   return queryInterface.bulkDelete('Spots', null, {});
  }
};
